/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs.handmail.panelmail;

import cs.handmail.login.CenterMail;
import cs.handmail.mail.SessionEmail;
import cs.handmail.processtable.TableListEmail;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;

/**
 *
 * @author Nguyen Van Cuong
 */
public class InBox extends javax.swing.JPanel {

    private int flags;
    private SessionEmail sessionEmail;
    private TableListEmail tableListEmail;
    private boolean timeout;

    /**
     * Creates new form InBox
     *
     * @param flags
     * @param session
     */
    public InBox(int flags, SessionEmail session) {
        initComponents();
        this.flags = flags;
        sessionEmail = session;
        tableListEmail = new TableListEmail();
        timeout = true;
        switch (this.flags) {
            case CenterMail.CUSTOMER:
                title.setText("Customer");
                break;
            case CenterMail.STAFF:
                title.setText("Staff");
                break;
            case CenterMail.SENT:
                title.setText("Send");
                break;
            case CenterMail.DELETEINBOX:
                title.setText("Delete Inbox");
                break;
            case CenterMail.DELETESENT:
                title.setText("Delete Send");
                break;
        }

        Thread th = new Thread() {
            @Override
            public void run() {
                while (timeout) {
                    try {
                        updateEmail();
                        load.setVisible(false);
                        Thread.sleep(60000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(InBox.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        };
        th.start();
    }

    public void updateEmail() {
        Message message[] = null;
        switch (flags) {
            case CenterMail.CUSTOMER:
                message = sessionEmail.getMessageCustomer();
                break;
            case CenterMail.STAFF:
                message = sessionEmail.getMessageStaff();
                break;
            case CenterMail.SENT:
                message = sessionEmail.getMessageSent();
                break;
            case CenterMail.DELETEINBOX:
                message = sessionEmail.getMessageDeleteInbox();
                break;
            case CenterMail.DELETESENT:
                message = sessionEmail.getMessageDeleteSent();
                break;
        }
        tableListEmail.displayEmail(table, message);
    }

    public void close() {
        timeout = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        load = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setForeground(java.awt.SystemColor.activeCaption);
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(419, 43));

        load.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loader-newui.gif"))); // NOI18N

        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setText("Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(load))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(load, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "STT", "Date", "From", "Subject"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel load;
    private javax.swing.JTable table;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
